package com.ichunming.mg.model;

import java.util.Date;

public class Album {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.title
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer viewcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer likecnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer replycnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.id
     *
     * @return the value of album.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.id
     *
     * @param id the value for album.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.title
     *
     * @return the value of album.title
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.title
     *
     * @param title the value for album.title
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.author
     *
     * @return the value of album.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.author
     *
     * @param author the value for album.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.introduce
     *
     * @return the value of album.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.introduce
     *
     * @param introduce the value for album.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.tag
     *
     * @return the value of album.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.tag
     *
     * @param tag the value for album.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.viewCnt
     *
     * @return the value of album.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getViewcnt() {
        return viewcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.viewCnt
     *
     * @param viewcnt the value for album.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setViewcnt(Integer viewcnt) {
        this.viewcnt = viewcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.likeCnt
     *
     * @return the value of album.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getLikecnt() {
        return likecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.likeCnt
     *
     * @param likecnt the value for album.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setLikecnt(Integer likecnt) {
        this.likecnt = likecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.replyCnt
     *
     * @return the value of album.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getReplycnt() {
        return replycnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.replyCnt
     *
     * @param replycnt the value for album.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setReplycnt(Integer replycnt) {
        this.replycnt = replycnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.createDate
     *
     * @return the value of album.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.createDate
     *
     * @param createdate the value for album.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.updateDate
     *
     * @return the value of album.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.updateDate
     *
     * @param updatedate the value for album.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}