package com.ichunming.mg.model;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer viewcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer likecnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer replycnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author
     *
     * @return the value of article.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author
     *
     * @param author the value for article.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.introduce
     *
     * @return the value of article.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.introduce
     *
     * @param introduce the value for article.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tag
     *
     * @return the value of article.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tag
     *
     * @param tag the value for article.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.viewCnt
     *
     * @return the value of article.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getViewcnt() {
        return viewcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.viewCnt
     *
     * @param viewcnt the value for article.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setViewcnt(Integer viewcnt) {
        this.viewcnt = viewcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.likeCnt
     *
     * @return the value of article.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getLikecnt() {
        return likecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.likeCnt
     *
     * @param likecnt the value for article.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setLikecnt(Integer likecnt) {
        this.likecnt = likecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.replyCnt
     *
     * @return the value of article.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getReplycnt() {
        return replycnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.replyCnt
     *
     * @param replycnt the value for article.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setReplycnt(Integer replycnt) {
        this.replycnt = replycnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.createDate
     *
     * @return the value of article.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.createDate
     *
     * @param createdate the value for article.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updateDate
     *
     * @return the value of article.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.updateDate
     *
     * @param updatedate the value for article.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.status
     *
     * @return the value of article.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.status
     *
     * @param status the value for article.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}