package com.ichunming.mg.model;

import java.util.Date;

public class LikeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.uid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.type
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.rid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Long rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.id
     *
     * @return the value of like_record.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.id
     *
     * @param id the value for like_record.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.uid
     *
     * @return the value of like_record.uid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.uid
     *
     * @param uid the value for like_record.uid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.type
     *
     * @return the value of like_record.type
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.type
     *
     * @param type the value for like_record.type
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.rid
     *
     * @return the value of like_record.rid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.rid
     *
     * @param rid the value for like_record.rid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.status
     *
     * @return the value of like_record.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.status
     *
     * @param status the value for like_record.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.createDate
     *
     * @return the value of like_record.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.createDate
     *
     * @param createdate the value for like_record.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}