package com.ichunming.mg.model;

import java.util.Date;

public class Multimedia {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.title
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.pic
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.src
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer viewcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer likecnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer replycnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.id
     *
     * @return the value of multimedia.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.id
     *
     * @param id the value for multimedia.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.title
     *
     * @return the value of multimedia.title
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.title
     *
     * @param title the value for multimedia.title
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.author
     *
     * @return the value of multimedia.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.author
     *
     * @param author the value for multimedia.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.introduce
     *
     * @return the value of multimedia.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.introduce
     *
     * @param introduce the value for multimedia.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.pic
     *
     * @return the value of multimedia.pic
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.pic
     *
     * @param pic the value for multimedia.pic
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.src
     *
     * @return the value of multimedia.src
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.src
     *
     * @param src the value for multimedia.src
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.tag
     *
     * @return the value of multimedia.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.tag
     *
     * @param tag the value for multimedia.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.viewCnt
     *
     * @return the value of multimedia.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getViewcnt() {
        return viewcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.viewCnt
     *
     * @param viewcnt the value for multimedia.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setViewcnt(Integer viewcnt) {
        this.viewcnt = viewcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.likeCnt
     *
     * @return the value of multimedia.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getLikecnt() {
        return likecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.likeCnt
     *
     * @param likecnt the value for multimedia.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setLikecnt(Integer likecnt) {
        this.likecnt = likecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.replyCnt
     *
     * @return the value of multimedia.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getReplycnt() {
        return replycnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.replyCnt
     *
     * @param replycnt the value for multimedia.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setReplycnt(Integer replycnt) {
        this.replycnt = replycnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.createDate
     *
     * @return the value of multimedia.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.createDate
     *
     * @param createdate the value for multimedia.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.updateDate
     *
     * @return the value of multimedia.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.updateDate
     *
     * @param updatedate the value for multimedia.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.status
     *
     * @return the value of multimedia.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.status
     *
     * @param status the value for multimedia.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}