package com.ichunming.mg.model;

import java.util.Date;

public class Photo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.src
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer viewcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer likecnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer replycnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.id
     *
     * @return the value of photo.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.id
     *
     * @param id the value for photo.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.author
     *
     * @return the value of photo.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.author
     *
     * @param author the value for photo.author
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.introduce
     *
     * @return the value of photo.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.introduce
     *
     * @param introduce the value for photo.introduce
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.src
     *
     * @return the value of photo.src
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.src
     *
     * @param src the value for photo.src
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.tag
     *
     * @return the value of photo.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.tag
     *
     * @param tag the value for photo.tag
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.viewCnt
     *
     * @return the value of photo.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getViewcnt() {
        return viewcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.viewCnt
     *
     * @param viewcnt the value for photo.viewCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setViewcnt(Integer viewcnt) {
        this.viewcnt = viewcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.likeCnt
     *
     * @return the value of photo.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getLikecnt() {
        return likecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.likeCnt
     *
     * @param likecnt the value for photo.likeCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setLikecnt(Integer likecnt) {
        this.likecnt = likecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.replyCnt
     *
     * @return the value of photo.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getReplycnt() {
        return replycnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.replyCnt
     *
     * @param replycnt the value for photo.replyCnt
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setReplycnt(Integer replycnt) {
        this.replycnt = replycnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.createDate
     *
     * @return the value of photo.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.createDate
     *
     * @param createdate the value for photo.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.updateDate
     *
     * @return the value of photo.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.updateDate
     *
     * @param updatedate the value for photo.updateDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.status
     *
     * @return the value of photo.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.status
     *
     * @param status the value for photo.status
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}