package com.ichunming.mg.model;

import java.util.Date;

public class Reply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.uid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.type
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.rid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Long rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.content
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.id
     *
     * @return the value of reply.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.id
     *
     * @param id the value for reply.id
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.uid
     *
     * @return the value of reply.uid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.uid
     *
     * @param uid the value for reply.uid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.type
     *
     * @return the value of reply.type
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.type
     *
     * @param type the value for reply.type
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.rid
     *
     * @return the value of reply.rid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.rid
     *
     * @param rid the value for reply.rid
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.content
     *
     * @return the value of reply.content
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.content
     *
     * @param content the value for reply.content
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.createDate
     *
     * @return the value of reply.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.createDate
     *
     * @param createdate the value for reply.createDate
     *
     * @mbggenerated Tue Nov 29 18:11:36 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}