package com.ichunming.mg.model;

import java.util.Date;

public class VerifyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_info.id
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_info.receiver
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_info.type
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_info.content
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_info.expire_date
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    private Date expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_info.create_date
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_info.id
     *
     * @return the value of verify_info.id
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_info.id
     *
     * @param id the value for verify_info.id
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_info.receiver
     *
     * @return the value of verify_info.receiver
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_info.receiver
     *
     * @param receiver the value for verify_info.receiver
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_info.type
     *
     * @return the value of verify_info.type
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_info.type
     *
     * @param type the value for verify_info.type
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_info.content
     *
     * @return the value of verify_info.content
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_info.content
     *
     * @param content the value for verify_info.content
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_info.expire_date
     *
     * @return the value of verify_info.expire_date
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_info.expire_date
     *
     * @param expireDate the value for verify_info.expire_date
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_info.create_date
     *
     * @return the value of verify_info.create_date
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_info.create_date
     *
     * @param createDate the value for verify_info.create_date
     *
     * @mbggenerated Fri Nov 18 16:53:50 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}